### ISSUE TITLE
Fix failure when running tests with KeyError: <type 'unicode'>

### ISSUE THREAD

**Issue by malrusha** [pennsignals/aptos#10]
Running tests fail with python 2.7.13 

[result.txt](https://github.com/pennsignals/aptos/files/1334623/result.txt)

**Comment by rightlag** [comment]
Hi @malrusha, `aptos` currently does not support Python versions `2.7.x`. You can either install Python 3 directly or via a Python [virtual environment](http://docs.python-guide.org/en/latest/dev/virtualenvs/).

Please let me know if you continue to experience this issue.

**Comment by malrusha** [comment]
@rightlag works with python3. Thanks!
