### ISSUE TITLE
Add instruction on using CLI in windows prompt

### ISSUE THREAD

**Issue by TheWindRider** [pennsignals/aptos#11]
The example script in the Data Validation CLI section needs a little adaptation to work in windows prompt, otherwise double quotes won't be recognized and error will be reported as screenshot at bottom. 

I may contribute an easy solution for windows to the README, but I don't know how to apply font color to output message in windows prompt. 

![validate_cli](https://user-images.githubusercontent.com/12599488/32587029-03e2eed0-c4bb-11e7-93be-5f4364bdcfb2.PNG)

**Comment by TheWindRider** [comment]
@gitmagic-bot Looks like I don't have permission to add labels?

**Comment by rightlag** [comment]
Hi @TheWindRider, thanks for reporting this. I think updating the README is a good idea.

As for coloring terminal output, I'm currently using the [`TermColors`](https://github.com/pennsignals/aptos/blob/master/aptos/__main__.py#L11) class. However, I think the `__main__` module could be cleaned up a bit. I also found the [`termcolor`](https://pypi.python.org/pypi/termcolor) module on PyPI and think it might be a better solution than using the `TermColors` class.

Any thoughts?

**Comment by TheWindRider** [comment]
Ok I will work on the README.  @rightlag Would you prefer a new pair of screenshots, or more low-key modification like one line of example code that works in windows terminal? 

I don't have good knowledge about the PyPI unfortunately.

**Comment by rightlag** [comment]
Just adding the Windows command should be fine. Could you also add headers above the commands (e.g.):

## macOS

    $ command

## Windows

    > command
