### ISSUE TITLE
Replace TermColors class with termcolor and colorama modules

### ISSUE THREAD

**Issue by TheWindRider** [pennsignals/aptos#14]
In a previous issue #11, @rightlag suggested using `termcolor` instead of the current solution.  I did a little search, found [this Stackoverflow post](https://stackoverflow.com/questions/21858567/why-does-termcolor-output-control-characters-instead-of-colored-text-in-the-wind), seems not hard.  And I plan to implement it in the `__main__.py`.

**Comment by rightlag** [comment]
@TheWindRider thanks for this!
