### ISSUE TITLE
Add Swagger v3 parsing

### ISSUE THREAD

**Issue by jasonwalsh** [pennsignals/aptos#3]
I'd like to add support for parsing Swagger (OpenAPI) [Specifications](https://swagger.io/specification/). Swagger uses JSON Schema and supports *most* primitive [data types](https://swagger.io/specification/#dataTypes), so the [`primitive.Creator`](https://github.com/pennsignals/aptos/blob/master/aptos/primitive.py#L12) class factory can be used to create and unmarshal schema instances.

Advantages of adding support for Swagger:

- Provides a way of documenting existing APIs, in particular, HTTP APIs
- Adds the ability to validate HTTP response payloads (JSON-formatted)
- Can reuse existing code to convert Swagger [components](https://swagger.io/specification/#componentsObject) into different data-interchange formats

I envision the flowchart for this functionality to look like this:

<p align="center">
    <img src="https://cdn-images-1.medium.com/max/2000/1*8Z2-Y9yY8PcNQ4n9cOhUGA.png">
</p>

Swagger specifications use [`responses`](https://swagger.io/specification/#responsesObject) objects to define the expected responses returned from the HTTP API.

[Here](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml#L35) is an example of an expected response from the `GET /pets` endpoint. `aptos` could validate the HTTP response body using the [`visitor.ValidaitionVisitor`](https://github.com/pennsignals/aptos/blob/master/aptos/visitor.py#L22) class.

I will create a new branch for this proposed prototype.

## OpenAPI Schema

- [x] [OpenAPI Object](https://swagger.io/specification/#oasObject)
- [x] [Info Object](https://swagger.io/specification/#infoObject)
- [x] [Contact Object](https://swagger.io/specification/#contactObject)
- [x] [License Object](https://swagger.io/specification/#licenseObject)
- [x] [Server Object](https://swagger.io/specification/#serverObject)
- [x] [Server Variable Object](https://swagger.io/specification/#serverVariableObject)
- [x] [Components Object](https://swagger.io/specification/#componentsObject)
- [x] [Paths Object](https://swagger.io/specification/#pathsObject)
- [x] [Path Item Object](https://swagger.io/specification/#pathItemObject)
- [x] [Operation Object](https://swagger.io/specification/#operationObject)
- [x] [External Documentation Object](https://swagger.io/specification/#externalDocumentationObject)
- [x] [Parameter Object](https://swagger.io/specification/#parameterObject)
- [x] [Request Body Object](https://swagger.io/specification/#requestBodyObject)
- [x] [Media Type Object](https://swagger.io/specification/#mediaTypeObject)
- [x] [Encoding Object](https://swagger.io/specification/#encodingObject)
- [x] [Responses Object](https://swagger.io/specification/#responsesObject)
- [x] [Response Object](https://swagger.io/specification/#responseObject)
- [x] [Callback Object](https://swagger.io/specification/#callbackObject)
- [x] [Example Object](https://swagger.io/specification/#exampleObject)
- [x] [Link Object](https://swagger.io/specification/#linkObject)
- [x] [Header Object](https://swagger.io/specification/#headerObject)
- [x] [Tag Object](https://swagger.io/specification/#tagObject)
- [x] [Reference Object](https://swagger.io/specification/#referenceObject)
- [ ] [Schema Object](https://swagger.io/specification/#schemaObject)
- [x] [Discriminator Object](https://swagger.io/specification/#discriminatorObject)
- [x] [XML Object](https://swagger.io/specification/#xmlObject)
- [x] [Security Scheme Object](https://swagger.io/specification/#securitySchemeObject)
- [x] [OAuth Flows Object](https://swagger.io/specification/#oauthFlowsObject)
- [x] [OAuth Flow Object](https://swagger.io/specification/#oauthFlowObject)
- [x] [Security Requirement Object](https://swagger.io/specification/#securityRequirementObject)

**Comment by rightlag** [comment]
As an update, I've created branch [`feature/swagger-3`](https://github.com/pennsignals/aptos/tree/feature/swagger-3) to begin the initial prototype work for this feature.
