### ISSUE TITLE
Getting unicode error while parsing with avro schema

### ISSUE THREAD

**Issue by kchandan** [pennsignals/aptos#9]
I just downloaded and installed the tool, but when I am trying to validate against my schema it throws

omponent = SchemaParser.parse(schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/aptos/parser.py", line 16, in parse
    component = Creator.create(schema.get('type')).unmarshal(schema)
  File "/usr/lib/python2.7/site-packages/aptos/primitive.py", line 28, in create
    }[identifier.__class__](identifier)
KeyError: <type 'unicode'>

I dont have any special character that requires unicode in the my data or schema. Is it possible to pass it as variable?

**Comment by rightlag** [comment]
Hey @kchandan, thanks for opening this. Out of curiosity which version of Python are you using?

**Comment by kchandan** [comment]
Python 2.7.5 on CentOS 7

**Comment by rightlag** [comment]
@kchandan aptos only supports Python >=3.5. There is a `python_requires` keyword for [setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html) that should be added to the [`setup.py`](https://github.com/pennsignals/aptos/blob/master/setup.py) module (e.g. `python_requires='>=3.5'`).

Would you mind submitting a PR for this?

**Comment by kchandan** [comment]
I don't have python 3.5 installed but when I try to use python_requires clause in the setup.py I am getting below error

python setup.py
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by rightlag** [comment]
You would need to run `python setup.py install` to install the module locally. setuptools should then detect the version of Python and throw an exception for Python versions < 3.5.

I'll submit a PR.

**Comment by rightlag** [comment]
@kchandan I've added the `python_requires` keyword to the setup module. See 3cad2a5 for details. You'll need Python >=3.5 to install aptos. You can create a Python [virtual environment](http://docs.python-guide.org/en/latest/dev/virtualenvs/) that uses Python >=3.5.
